services:
  # 1. L-Backend (API)
  - type: web
    name: flask-api
    env: docker
    dockerContext: .
    dockerFilePath: Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 app:app

  # 2. L-AI Agent (Celery Worker)
  - type: worker
    name: ai-agent-worker
    env: docker
    dockerContext: .
    dockerFilePath: Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
    startCommand: celery -A worker.celery worker --loglevel=info

  # 3. Redis (L-Wasit)
  - type: redis
    name: redis-broker
    ipAllowList: [] # Allow all internal
